[package]
name = "py-xqdb"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition = "2021"

[lib]
name = "xqdb"
crate-type = ["cdylib"]

[dependencies]
xqdb = { path = "../crates/xqdb" }
pyo3 = { version = "0.29.2", features = ["chrono", "abi3-py310"] }
thiserror = { workspace = true }
polars-arrow.workspace = true
chrono = { workspace = true }
indexmap = { workspace = true }

[dependencies.polars]
workspace = true
