[package]
name = "xqdb"
version.workspace = true
authors.workspace = true
edition = "2021"
license = "BSD-3-Clause"
description = "a Rust library to interface to q"
repository.workspace = true

[lib]
name = "xqdb"
crate-type = ["lib"]

[dependencies]
rustls = { version = "0.23", features = ["ring"] }
rustls-platform-verifier = "0.7"
chrono = { workspace = true }
polars-arrow = { workspace = true }
polars-buffer = { workspace = true, default-features = false }
thiserror = { workspace = true }
rayon = "1.12.0"
uuid = { workspace = true }
lz4_flex = { version = "0.14.0", features = ["frame"] }
indexmap = { workspace = true }
bytemuck = "1.25"
memchr = "2.8"

[dependencies.polars]
workspace = true
features = [
  "dtype-categorical",
  "dtype-array",
  "dtype-duration",
  "dtype-u8",
  "dtype-i16",
  "dtype-datetime",
  "dtype-date",
  "dtype-time",
  "ipc",
  "ipc_streaming",
]

[dependencies.xxhash-rust]
version = "0.8.15"
features = ["xxh3", "const_xxh3", "xxh32"]
